# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example-sdk-module' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example-sdk-module

  target 'example-sdk-module-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'example-sdk-moduleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'example-sdk-module-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for example-sdk-module-tvOS

  target 'example-sdk-module-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
